name: "Quality assurance"
on:
  push: ~

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          docker compose up -d
          docker compose exec app composer install -n
          bin/docker.sh vendor/bin/php-cs-fixer check --allow-risky=yes
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          bin/setup-dev.sh
          bin/docker.sh vendor/bin/phpunit
